# Generated by Django 5.0.6 on 2024-06-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens_lista_compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlistacompra',
            old_name='lista_compra',
            new_name='lista_compra_id',
        ),
        migrations.RenameField(
            model_name='itemlistacompra',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
