# Generated by Django 5.0.6 on 2024-06-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preco',
            old_name='mercado',
            new_name='mercado_id',
        ),
        migrations.RenameField(
            model_name='preco',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
